-- MySQL Script generated by MySQL Workbench
-- Mon Nov  3 10:32:27 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema SIGECO
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SIGECO
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SIGECO` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `SIGECO` ;

-- -----------------------------------------------------
-- Table `SIGECO`.`tipo_host`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIGECO`.`tipo_host` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_host` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SIGECO`.`nombre_host`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIGECO`.`nombre_host` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `tipo_host_id` INT NOT NULL,
  `costo` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `tipo_host_id` (`tipo_host_id` ASC) VISIBLE,
  CONSTRAINT `nombre_host_ibfk_1`
    FOREIGN KEY (`tipo_host_id`)
    REFERENCES `SIGECO`.`tipo_host` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SIGECO`.`almacenamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIGECO`.`almacenamiento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_host_id` INT NOT NULL,
  `detalles` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `nombre_host_id` (`nombre_host_id` ASC) VISIBLE,
  CONSTRAINT `almacenamiento_ibfk_1`
    FOREIGN KEY (`nombre_host_id`)
    REFERENCES `SIGECO`.`nombre_host` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SIGECO`.`complejidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIGECO`.`complejidad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nivel` ENUM('baja', 'media', 'alta') NOT NULL,
  `cantidad_dias` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SIGECO`.`proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIGECO`.`proyecto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_proyecto` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `complejidad_id` INT NULL DEFAULT NULL,
  `fecha_inicializacion` DATE NULL DEFAULT curdate(),
  PRIMARY KEY (`id`),
  INDEX `complejidad_id` (`complejidad_id` ASC) VISIBLE,
  CONSTRAINT `proyecto_ibfk_1`
    FOREIGN KEY (`complejidad_id`)
    REFERENCES `SIGECO`.`complejidad` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SIGECO`.`tipo_cobro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIGECO`.`tipo_cobro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `tarifa` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SIGECO`.`modalidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIGECO`.`modalidad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `porcentaje` DECIMAL(5,2) NULL DEFAULT '0.00',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SIGECO`.`capacitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIGECO`.`capacitacion` (
  `proyecto_id` INT NOT NULL,
  `tipo_cobro_id` INT NULL DEFAULT NULL,
  `duracion` DECIMAL(10,2) NULL DEFAULT NULL,
  `horas_dia` DECIMAL(5,2) NULL DEFAULT NULL,
  `modalidad_id` INT NULL DEFAULT NULL,
  `logistica` DECIMAL(10,2) NULL DEFAULT NULL,
  `fecha_inicio` DATE NULL DEFAULT NULL,
  `fecha_finalizacion` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`proyecto_id`),
  INDEX `tipo_cobro_id` (`tipo_cobro_id` ASC) VISIBLE,
  INDEX `modalidad_id` (`modalidad_id` ASC) VISIBLE,
  CONSTRAINT `capacitacion_ibfk_1`
    FOREIGN KEY (`proyecto_id`)
    REFERENCES `SIGECO`.`proyecto` (`id`),
  CONSTRAINT `capacitacion_ibfk_2`
    FOREIGN KEY (`tipo_cobro_id`)
    REFERENCES `SIGECO`.`tipo_cobro` (`id`),
  CONSTRAINT `capacitacion_ibfk_3`
    FOREIGN KEY (`modalidad_id`)
    REFERENCES `SIGECO`.`modalidad` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SIGECO`.`rango`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIGECO`.`rango` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_rango` VARCHAR(50) NOT NULL,
  `nivel` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SIGECO`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIGECO`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NULL DEFAULT NULL,
  `usuario` VARCHAR(50) NOT NULL,
  `contrasena` VARCHAR(255) NOT NULL,
  `rango_id` INT NULL DEFAULT NULL,
  `correo` VARCHAR(100) NULL DEFAULT NULL,
  `fecha_registro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `usuario` (`usuario` ASC) VISIBLE,
  INDEX `rango_id` (`rango_id` ASC) VISIBLE,
  CONSTRAINT `usuarios_ibfk_1`
    FOREIGN KEY (`rango_id`)
    REFERENCES `SIGECO`.`rango` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SIGECO`.`asignacion_capacitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIGECO`.`asignacion_capacitacion` (
  `capacitacion_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  `rol` VARCHAR(50) NULL DEFAULT NULL,
  `horas_trabajadas` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`capacitacion_id`, `usuarios_id`),
  INDEX `usuarios_id` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `asignacion_capacitacion_ibfk_1`
    FOREIGN KEY (`capacitacion_id`)
    REFERENCES `SIGECO`.`capacitacion` (`proyecto_id`),
  CONSTRAINT `asignacion_capacitacion_ibfk_2`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `SIGECO`.`usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SIGECO`.`tipo_documentacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIGECO`.`tipo_documentacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_documentacion` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SIGECO`.`asignacion_documentacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIGECO`.`asignacion_documentacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `proyecto_id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  `rol` VARCHAR(50) NULL DEFAULT NULL,
  `horas_trabajadas` DECIMAL(10,2) NULL DEFAULT NULL,
  `tipo_documentacion_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `proyecto_id` (`proyecto_id` ASC) VISIBLE,
  INDEX `usuarios_id` (`usuarios_id` ASC) VISIBLE,
  INDEX `tipo_documentacion_id` (`tipo_documentacion_id` ASC) VISIBLE,
  CONSTRAINT `asignacion_documentacion_ibfk_1`
    FOREIGN KEY (`proyecto_id`)
    REFERENCES `SIGECO`.`proyecto` (`id`),
  CONSTRAINT `asignacion_documentacion_ibfk_2`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `SIGECO`.`usuarios` (`id`),
  CONSTRAINT `asignacion_documentacion_ibfk_3`
    FOREIGN KEY (`tipo_documentacion_id`)
    REFERENCES `SIGECO`.`tipo_documentacion` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SIGECO`.`asignacion_proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIGECO`.`asignacion_proyecto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuarios_id` INT NOT NULL,
  `proyecto_id` INT NOT NULL,
  `horas_trabajadas` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `usuarios_id` (`usuarios_id` ASC) VISIBLE,
  INDEX `proyecto_id` (`proyecto_id` ASC) VISIBLE,
  CONSTRAINT `asignacion_proyecto_ibfk_1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `SIGECO`.`usuarios` (`id`),
  CONSTRAINT `asignacion_proyecto_ibfk_2`
    FOREIGN KEY (`proyecto_id`)
    REFERENCES `SIGECO`.`proyecto` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SIGECO`.`costos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIGECO`.`costos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `proyecto_id` INT NOT NULL,
  `almacenamiento_id` INT NULL DEFAULT NULL,
  `costo_proyecto` DECIMAL(15,2) NULL DEFAULT NULL,
  `fecha_finalizacion` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `proyecto_id` (`proyecto_id` ASC) VISIBLE,
  INDEX `almacenamiento_id` (`almacenamiento_id` ASC) VISIBLE,
  CONSTRAINT `costos_ibfk_1`
    FOREIGN KEY (`proyecto_id`)
    REFERENCES `SIGECO`.`proyecto` (`id`),
  CONSTRAINT `costos_ibfk_2`
    FOREIGN KEY (`almacenamiento_id`)
    REFERENCES `SIGECO`.`almacenamiento` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SIGECO`.`documentacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIGECO`.`documentacion` (
  `proyecto_id` INT NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `ruta_archivo` VARCHAR(255) NULL DEFAULT NULL,
  `fecha_creacion` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`proyecto_id`),
  CONSTRAINT `documentacion_ibfk_1`
    FOREIGN KEY (`proyecto_id`)
    REFERENCES `SIGECO`.`proyecto` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SIGECO`.`modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIGECO`.`modulo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `proyecto_id` INT NOT NULL,
  `nombre_modulo` VARCHAR(100) NOT NULL,
  `fecha_creacion` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `proyecto_id` (`proyecto_id` ASC) VISIBLE,
  CONSTRAINT `modulo_ibfk_1`
    FOREIGN KEY (`proyecto_id`)
    REFERENCES `SIGECO`.`proyecto` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SIGECO`.`programador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIGECO`.`programador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuarios_id` INT NOT NULL,
  `costo_hora` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `usuarios_id` (`usuarios_id` ASC) VISIBLE,
  CONSTRAINT `programador_ibfk_1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `SIGECO`.`usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SIGECO`.`tecnologia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIGECO`.`tecnologia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `suma_porcentaje` DECIMAL(5,2) NULL DEFAULT '0.00',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SIGECO`.`programador_tecnologia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIGECO`.`programador_tecnologia` (
  `programador_id` INT NOT NULL,
  `tecnologia_id` INT NOT NULL,
  `nivel_conocimiento` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`programador_id`, `tecnologia_id`),
  INDEX `tecnologia_id` (`tecnologia_id` ASC) VISIBLE,
  CONSTRAINT `programador_tecnologia_ibfk_1`
    FOREIGN KEY (`programador_id`)
    REFERENCES `SIGECO`.`programador` (`id`),
  CONSTRAINT `programador_tecnologia_ibfk_2`
    FOREIGN KEY (`tecnologia_id`)
    REFERENCES `SIGECO`.`tecnologia` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SIGECO`.`proyecto_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIGECO`.`proyecto_log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `proyecto_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `accion` VARCHAR(255) NOT NULL,
  `detalle` TEXT NULL DEFAULT NULL,
  `fecha` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `proyecto_id` (`proyecto_id` ASC) VISIBLE,
  INDEX `usuario_id` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `proyecto_log_ibfk_1`
    FOREIGN KEY (`proyecto_id`)
    REFERENCES `SIGECO`.`proyecto` (`id`),
  CONSTRAINT `proyecto_log_ibfk_2`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `SIGECO`.`usuarios` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SIGECO`.`seguimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIGECO`.`seguimiento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `capacitacion_id` INT NOT NULL,
  `tipo` VARCHAR(50) NULL DEFAULT NULL,
  `tipo_cobro_id` INT NULL DEFAULT NULL,
  `duracion_horas` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `capacitacion_id` (`capacitacion_id` ASC) VISIBLE,
  INDEX `tipo_cobro_id` (`tipo_cobro_id` ASC) VISIBLE,
  CONSTRAINT `seguimiento_ibfk_1`
    FOREIGN KEY (`capacitacion_id`)
    REFERENCES `SIGECO`.`capacitacion` (`proyecto_id`),
  CONSTRAINT `seguimiento_ibfk_2`
    FOREIGN KEY (`tipo_cobro_id`)
    REFERENCES `SIGECO`.`tipo_cobro` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SIGECO`.`skill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SIGECO`.`skill` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tecnologia_id` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `suma_porcentaje` DECIMAL(5,2) NULL DEFAULT '0.00',
  PRIMARY KEY (`id`),
  INDEX `tecnologia_id` (`tecnologia_id` ASC) VISIBLE,
  CONSTRAINT `skill_ibfk_1`
    FOREIGN KEY (`tecnologia_id`)
    REFERENCES `SIGECO`.`tecnologia` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
